# Generated by Django 3.2.4 on 2022-04-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='content',
            field=models.TextField(),
        ),
    ]
